### ISSUE TITLE
Fingerprint is not showed

### ISSUE THREAD

**Issue by masalinas** [SergioSuarezDev/Ionic-Biometric-Capacitor#21]
Estoy emulando tu ejemplo contra un Nexus 5 API 30. Tras introducir la password y volver a meterla para pasar a la siguente vista el sistema no muestra la pregunta para activar el check de huella ni tampoco me dice que no este activo el sensor. ¿Que puede estar mal?

**Comment by SergioSuarezGil** [comment]
Quizás el problema esté en la version del plugin: https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio
Que no esté funcionando correctamente con el API 30.
¿Has probado a actualizar version a la v4.0.2?

De todos modos tengo pensado actualizar este repo y añadir nuevas versiones de todo, Ionic, Angular, plugin de fingerprint, etc. Inclusive añadir la clave encriptada al local storage. A ver si saco tiempo y añado la nueva version.
