### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by mayankkataria** [SergioSuarezDev/Ionic-Biometric-Capacitor#4]
* What went wrong:
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not find com.github.JesusM:FingerprintManager:v2.0.2.

**Comment by SergioSuarezGil** [comment]
Hi i'm going to check it out and tell you something soon 👍

**Comment by SergioSuarezGil** [comment]
The project has been updated with new versions of Ionic and Angular, and now a more stable plugin is used for the Fingerprint.
